# Generated by Django 5.1.6 on 2025-03-29 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_class_info_complete_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='class_info_complete',
            new_name='class_selected',
        ),
        migrations.AddField(
            model_name='user',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.class'),
        ),
    ]
