# Generated by Django 5.1.6 on 2025-03-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_class_info_complete_user_class_selected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='class_selected',
        ),
    ]
