# Generated by Django 5.1.6 on 2025-03-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_class_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='program',
        ),
        migrations.RemoveField(
            model_name='user',
            name='section',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
    ]
